//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql2SqlCloner.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceServer
        {
            get
            {
                return ((string)(this["SourceServer"]));
            }
            set
            {
                this["SourceServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationServer
        {
            get
            {
                return ((string)(this["DestinationServer"]));
            }
            set
            {
                this["DestinationServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopySchema
        {
            get
            {
                return ((bool)(this["CopySchema"]));
            }
            set
            {
                this["CopySchema"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyData
        {
            get
            {
                return ((bool)(this["CopyData"]));
            }
            set
            {
                this["CopyData"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyConstraints
        {
            get
            {
                return ((bool)(this["CopyConstraints"]));
            }
            set
            {
                this["CopyConstraints"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DropAndRecreateObjects
        {
            get
            {
                return ((bool)(this["DropAndRecreateObjects"]));
            }
            set
            {
                this["DropAndRecreateObjects"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopySecurity
        {
            get
            {
                return ((bool)(this["CopySecurity"]));
            }
            set
            {
                this["CopySecurity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyExtendedProperties
        {
            get
            {
                return ((bool)(this["CopyExtendedProperties"]));
            }
            set
            {
                this["CopyExtendedProperties"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPermissions
        {
            get
            {
                return ((bool)(this["CopyPermissions"]));
            }
            set
            {
                this["CopyPermissions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyFullText
        {
            get
            {
                return ((bool)(this["CopyFullText"]));
            }
            set
            {
                this["CopyFullText"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StopIfErrors
        {
            get
            {
                return ((bool)(this["StopIfErrors"]));
            }
            set
            {
                this["StopIfErrors"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearDestinationDatabase
        {
            get
            {
                return ((bool)(this["ClearDestinationDatabase"]));
            }
            set
            {
                this["ClearDestinationDatabase"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ignore_collation")]
        public global::Sql2SqlCloner.Core.DataTransfer.SqlCollationAction CopyCollation
        {
            get
            {
                return ((global::Sql2SqlCloner.Core.DataTransfer.SqlCollationAction)(this["CopyCollation"]));
            }
            set
            {
                this["CopyCollation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableNotForReplication
        {
            get
            {
                return ((bool)(this["DisableNotForReplication"]));
            }
            set
            {
                this["DisableNotForReplication"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteDestinationTables
        {
            get
            {
                return ((bool)(this["DeleteDestinationTables"]));
            }
            set
            {
                this["DeleteDestinationTables"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreFileGroup
        {
            get
            {
                return ((bool)(this["IgnoreFileGroup"]));
            }
            set
            {
                this["IgnoreFileGroup"] = value;
            }
        }
    }
}
